labs/mvc/SportsStore Backup/SportsStore/Views/Shared/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System.Linq;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x));
        }
    }
}

labs/mvc/SportsStore Backup/SportsStore/Views/Shared/ProductSummary.cshtml
@model Product
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductID" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

labs/mvc/SportsStore Backup/SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet"
              asp-href-include="/lib/bootstrap/dist/**/*.min.css"
    asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <title>SportsStore</title>
    </head>
        <body>
        <div class="navbar navbar-inverse bg-inverse" role="navigation">
            <a class="navbar-brand" href="#">SPORTS STORE</a>
        </div>
        <div class="row m-1 p-1">
            <div id="categories" class="col-3">
                @await Component.InvokeAsync("NavigationMenu")
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </body>
</html>